### ISSUE TITLE
A small bug in _decrement function

### ISSUE THREAD

**Issue by wjdgns0914** [kritchie/LIBiFBTSVM#42]
I met an error when update iFBTSVM model multiple times with `ifbtsvm.update(X=X_train_svm, y=y_train_svm)`. 

```
Traceback (most recent call last):
  File "main_RF_SVM.py", line 156, in <module>
    ifbtsvm.update(X=chunk_arf.iloc[:, :-1].values, y=chunk_arf.iloc[:, -1].values)
  File "/usr/local/lib/python3.8/dist-packages/LIBiFBTSVM-2.0.0-py3.8.egg/libifbtsvm/libifbtsvm.py", line 362, in update
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 1046, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/LIBiFBTSVM-2.0.0-py3.8.egg/libifbtsvm/libifbtsvm.py", line 249, in _increment_dag_step
  File "/usr/local/lib/python3.8/dist-packages/LIBiFBTSVM-2.0.0-py3.8.egg/libifbtsvm/libifbtsvm.py", line 77, in _decrement
  File "<__array_function__ internals>", line 5, in delete
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/function_base.py", line 4480, in delete
    keep[obj,] = False
IndexError: index 35 is out of bounds for axis 0 with size 32
```

After thorough inspection, I found a small bug in `_decrement` function in libifbtsvm.py.
Please check my findings!

Original code block is as follows:
```python
@staticmethod
def _decrement(candidates, score, alphas, fuzzy, data) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    sco0 = np.delete(score[0], candidates)
    sco1 = np.delete(score[1], candidates)
    score = np.asarray([sco0, sco1])

    alphas = np.delete(alphas, candidates)
    fuzzy = np.delete(fuzzy, candidates)
    data = np.delete(data, candidates, axis=0)

    return score, alphas, fuzzy, data
```
The _decrement function in its current form is using the `candidates` to delete elements from `alphas`. However, `candidates` is an array of indices of `score`, not for `alphas` (`score[0]` and `alphas` are not in the same shape). So, we can't use `candidates` to delete elements in `alphas`  (or `fuzzy`, `data`). I think we should use `score` (for example `score[0][candidates]`) instead of `candidates` to do deletion on `alphas`, because `score[0]` is an array of indices for `alphas`.

I think we can modify the function as follows:

```python
@staticmethod
def _decrement(candidates, score, alphas, fuzzy, data) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    candidates_for_alphas = score[0][candidates].astype(int)
    alphas = np.delete(alphas, candidates_for_alphas)
    fuzzy = np.delete(fuzzy, candidates_for_alphas)
    data = np.delete(data, candidates_for_alphas, axis=0)

    sco0 = np.delete(score[0], candidates)
    for i in range(len(sco0)): # update index arrary about alphas, after deletion on alphas
        sco0[i] = sco0[i] - np.sum(score[0][candidates] <= sco0[i])
    sco1 = np.delete(score[1], candidates)
    score = np.asarray([sco0, sco1])
    return score, alphas, fuzzy, data
```

**Comment by kritchie** [comment]
Sorry for the delay :pray: (I'm not in a situation where it's easy to actively maintain this at the moment)

I'd like to reproduce this. I am surprised that our previous runs with various data sets didn't catch this type of error but looking at the description this might well be a bug :fearful: .  
Can you provide more information on the data set you are using and the conditions in which you are using the library ?

I'll try to get back to you as soon as I can. 

Thanks,

**Comment by wjdgns0914** [comment]
we can reproduce the error as belows:

```python
import pandas as pd
import numpy as np
from libifbtsvm import iFBTSVM, Hyperparameters
np.random.seed(333)
data = pd.read_csv('./Data/Robot24.csv').sample(frac=1)
idx_inst = np.round(np.linspace(0, data.shape[0], num = 40))

params = Hyperparameters(
    epsilon=0.0000001,
    fuzzy=0.01,
    C1=8,
    C2=2,
    C3=8,
    C4=2,
    max_iter=500,
    phi=0.00001,
    kernel=None,
    forget_score=10,
)

ifbtsvm = iFBTSVM(parameters=params, n_jobs=1)
for i_idx, _ in enumerate(idx_inst[:-1]):
    X_chunk = data.iloc[int(idx_inst[i_idx]):int(idx_inst[i_idx+1]),:-1]
    y_chunk = data.iloc[int(idx_inst[i_idx]):int(idx_inst[i_idx+1]),-1]
    if i_idx == 0:
        ifbtsvm.fit(X=X_chunk.values, y=y_chunk.values)
    else:
        ifbtsvm.update(X=X_chunk.values, y=y_chunk.values)
```

- dataset: robot24 (from https://archive.ics.uci.edu/dataset/194/wall+following+robot+navigation+data)
- The more finely you cut the data, the more frequently errors occur. So I split the dataset into 40 chunks

**Comment by kritchie** [comment]
Hi @wjdgns0914,

Thanks a lot for this. I was able to reproduce and it is indeed a bug ! :fearful: 
That's a very good catch :ok_hand: 

Would you be willing to submit a PR ? I'll be able to review it quickly.
